apiVersion: v1
kind: ConfigMap
metadata:
  name: watchgpt-config
  namespace: watchgpt
data:
  PORT: "8080"
  REDIS_ADDR: "redis:6379"
  COGNITO_REGION: "<REGION>"
  COGNITO_USER_POOL_ID: "<USER_POOL_ID>"
  COGNITO_APP_CLIENT_ID: "<APP_CLIENT_ID>"
